coverage:
  range: 80...100
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        target: 85%
ignore:
  - "**/*.test.js" 
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]